{{ if index .Values "cf-summit-2023-infra" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-summit-2023-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:cardano-foundation/cf-cardano-ballot.git
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: deploy/cf-cardano-ballot-infra
    helm:
      {{- with index .Values "cf-summit-2023-infra" }}
      values: |
{{ toYaml . | indent 8 }}
      {{- end }}

  ignoreDifferences:
    - group: "*"
      kind: "Secret"
      jqPathExpressions:
        - '.data'

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  destination:
    namespace: cf-summit-2023
    server: {{ .Values.spec.destination.server }}
{{ end }}
