{{ if index .Values "cf-cardano-ballot-voting-api" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-cardano-ballot-voting-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:cardano-foundation/cf-cardano-ballot.git
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: deploy/cf-cardano-ballot-voting-api
    helm:
      parameters:
        - name: "domain"
          value: {{ .Values.domain }}
        - name: "network"
          value: {{ .Values.network }}
      {{- with index .Values "cf-cardano-ballot-voting-api" "values" }}
      values: |
{{ toYaml . | indent 8 }}
      {{- end }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: cf-cardano-ballot
    server: {{ .Values.spec.destination.server }}
{{ end }}
