server:
  port: 9095

spring:
  application:
    name: candidate-app
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      minimum-idle: ${DB_MIN_IDLE:3}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
      idle-timeout: ${DB_IDLE_TIMEOUT:30000}
  flyway:
    locations: classpath:db/migration/postgresql
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    baselineOnMigrate: true
    enabled: true

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
