FROM gradle:jdk21-alpine AS build
WORKDIR /app
COPY . /app
RUN chmod +x gradlew
RUN ./gradlew clean build -x test

FROM openjdk:21-jdk-slim AS runtime
WORKDIR /app
COPY --from=build /app/build/libs/*SNAPSHOT.jar /app/app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
