FROM gradle:jdk21-alpine AS build
WORKDIR /app
COPY . /app
RUN chmod +x gradlew
RUN ./gradlew clean build -x test

FROM openjdk:21-jdk-slim AS runtime
WORKDIR /app
COPY --from=build /app/build/libs/*SNAPSHOT.jar /app/app.jar
CMD java \
  -Dspring.datasource.url=${SPRING_DATASOURCE_URL} \
  -Dspring.datasource.username=${SPRING_DATASOURCE_USERNAME} \
  -Dspring.datasource.password=${SPRING_DATASOURCE_PASSWORD} \
  -Dserver.port=${SERVER_PORT} \
  -jar app.jar
