version: '3.8'
services:
  follower-api:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/voting-ledger-follower-app:0.2.75
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
      - CARDANO_NETWORK=PREPROD
      - ORGANISER_STAKE_ADDRESS=stake_test1uqwcz0754wwpuhm6xhdpda6u9enyahaj5ynlc9ay5l4mlms4pyqyg
      - BIND_ON_EVENT_IDS=CIP-1694_Pre_Ratification_7AC8
      - YACI_STORE_CARDANO_SYNC_START_BLOCK_HASH=1705a8d8b69cb1315de2b7d5569953f0bb4eddb685cead76c98a6082e835f888
      - YACI_STORE_CARDANO_SYNC_START_SLOT=44150423
      - '9090:9090'
  verification-app:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/voting-verification-app:0.2.75
    restart: always
    environment:
      - LEDGER_FOLLOWER_APP_URL=http://follower-api:9090
      - CORS_ALLOWED_ORIGINS=http://localhost:8080
    ports:
      - '9092:9092'
  verification-ui:
    build:
      context: ui/verification-app
    environment:
      - REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL=http://localhost:9092
    restart: always
    ports:
      - '8080:8080'