import { get } from 'lodash';

// Services URLs
const VOTING_APP_SERVER_URL =
  process.env.REACT_APP_VOTING_APP_SERVER_URL || get(window, 'env.REACT_APP_VOTING_APP_SERVER_URL');
const VOTING_LEDGER_FOLLOWER_APP_SERVER_URL =
  process.env.REACT_APP_VOTING_LEDGER_FOLLOWER_APP_SERVER_URL ||
  get(window, 'env.REACT_APP_VOTING_LEDGER_FOLLOWER_APP_SERVER_URL');
const VOTING_VERIFICATION_APP_SERVER_URL =
  process.env.REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL ||
  get(window, 'env.REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL');
const VOTING_USER_VERIFICATION_SERVER_URL =
  process.env.REACT_APP_USER_VERIFICATION_SERVER_URL || get(window, 'env.REACT_APP_USER_VERIFICATION_SERVER_URL');
const FRONTEND_URL = process.env.REACT_APP_WEB_URL || get(window, 'env.REACT_APP_FRONTEND_URL');
const DISCORD_CHANNEL_URL =
  process.env.REACT_APP_DISCORD_CHANNEL_URL || get(window, 'env.REACT_APP_DISCORD_CHANNEL_URL');
const COMMIT_HASH = process.env.REACT_APP_COMMIT_HASH || get(window, 'env.REACT_APP_COMMIT_HASH');
const DISCORD_BOT_URL = process.env.REACT_APP_DISCORD_BOT_URL || get(window, 'env.REACT_APP_DISCORD_BOT_URL');
const DISCORD_SUPPORT_CHANNEL_URL =
  process.env.REACT_APP_DISCORD_SUPPORT_CHANNEL_URL || get(window, 'env.REACT_APP_DISCORD_SUPPORT_CHANNEL_URL');
// config vars
const TARGET_NETWORK = process.env.REACT_APP_TARGET_NETWORK || get(window, 'env.REACT_APP_TARGET_NETWORK');
const USING_FIXTURES = process.env.REACT_APP_TARGET_NETWORK || get(window, 'env.REACT_APP_USING_FIXTURES');
const EVENT_ID = process.env.REACT_APP_EVENT_ID || get(window, 'env.REACT_APP_EVENT_ID');
const APP_VERSION = process.env.REACT_APP_VERSION || get(window, 'env.REACT_APP_VERSION');
const SUPPORTED_WALLETS = (process.env.REACT_APP_SUPPORTED_WALLETS || get(window, 'env.REACT_APP_SUPPORTED_WALLETS'))
  .split(',')
  .filter((w) => !!w);
const SHOW_WINNERS = process.env.REACT_APP_SHOW_WINNERS || get(window, 'env.REACT_APP_SHOW_WINNERS');
const SHOW_HYDRA_TALLY = process.env.REACT_APP_SHOW_HYDRA_TALLY || get(window, 'env.REACT_APP_SHOW_HYDRA_TALLY');

export const env = {
  VOTING_APP_SERVER_URL,
  VOTING_LEDGER_FOLLOWER_APP_SERVER_URL,
  VOTING_VERIFICATION_APP_SERVER_URL,
  VOTING_USER_VERIFICATION_SERVER_URL,
  TARGET_NETWORK,
  USING_FIXTURES,
  EVENT_ID,
  APP_VERSION,
  SUPPORTED_WALLETS,
  FRONTEND_URL,
  COMMIT_HASH,
  DISCORD_CHANNEL_URL,
  DISCORD_BOT_URL,
  DISCORD_SUPPORT_CHANNEL_URL,
  SHOW_WINNERS,
  SHOW_HYDRA_TALLY
};
