apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-verification-service.fullname" . }}
  labels:
    {{- include "user-verification-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-verification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-verification-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: {{ .springProfiles }}
            - name: CARDANO_NETWORK
              value: {{ .Values.network | default "preprod" | upper}}
            - name: CORS_ALLOWED_ORIGINS
              value: {{ tpl $.Values.corsAllowedOrigins $ }}

            - name: AWS_SNS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sns-secrets
                  key: AWS_SNS_ACCESS_KEY_ID

            - name: AWS_SNS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sns-secrets
                  key: AWS_SNS_SECRET_ACCESS_KEY

            - name: AWS_SNS_REGION
              valueFrom:
                secretKeyRef:
                  name: sns-secrets
                  key: AWS_SNS_REGION

            - name: LEDGER_FOLLOWER_APP_URL
              value: {{ $.Values.ledgerFollowerAppUrl }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
