window.env = {};
window.env.REACT_APP_VERSION = `$REACT_APP_VERSION`;
window.env.REACT_APP_VOTING_APP_SERVER_URL = `$REACT_APP_VOTING_APP_SERVER_URL`;
window.env.REACT_APP_VOTING_LEDGER_FOLLOWER_APP_SERVER_URL = `$REACT_APP_VOTING_LEDGER_FOLLOWER_APP_SERVER_URL`;
window.env.REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL = `$REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL`;
window.env.REACT_APP_USER_VERIFICATION_SERVER_URL = `$REACT_APP_USER_VERIFICATION_SERVER_URL`;
window.env.REACT_APP_TARGET_NETWORK = `$REACT_APP_TARGET_NETWORK`;

window.env.REACT_APP_DISCORD_CHANNEL_URL = `$REACT_APP_DISCORD_CHANNEL_URL`;
window.env.REACT_APP_DISCORD_BOT_URL = `$REACT_APP_DISCORD_BOT_URL`;

window.env.REACT_APP_EVENT_ID = `$REACT_APP_EVENT_ID`;

window.env.REACT_APP_SUPPORTED_WALLETS = `$REACT_APP_SUPPORTED_WALLETS`;