replicaCount: 1

image:
  repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/user-verification-service
  tag: "0.0.1"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9093

ingress:
  enabled: true
  disableActuatorEndpoint: true
  additionalDomains: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

monitoring:
  enabled: true

discordBotEventIdBinding: ""
ledgerFollowerAppUrl: http://cf-cardano-ballot-ledger-follower-api-voting-ledger-follower-ap:9090
corsAllowedOrigins: https://{{ .Values.domain }}
dbSchema: user_verification
