{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cf-vote-commitment.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cf-vote-commitment.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "api.{{ .Values.domain }}"
      http:
        paths:
{{ if .Values.ingress.disableActuatorEndpoint }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: nginx-not-found
                port:
                  number: 80
{{ end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
  tls:
    - hosts:
        - "api.{{ .Values.domain }}"
{{ end }}
