{
 "title": "Voting Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Vote Cast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(resource_vote_count_seconds_count[$__rate_interval])) by (pod)",
     "legendFormat": "rps {{ pod }}"
    }
   ]
  },
  {
   "title": "Vote Count - Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (pod, le) (rate(resource_vote_count_seconds_bucket[10m])))",
     "legendFormat": "median - {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (pod, le) (rate(resource_vote_count_seconds_bucket[10m])))",
     "legendFormat": "p95 - {{pod}}"
    }
   ]
  },
  {
   "title": "Reference Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(resource_reference_events_seconds_count{exception=\"none\"}[$__rate_interval])) by (pod)",
     "legendFormat": "rps {{ pod }} - OK"
    },
    {
     "expr": "sum(rate(resource_reference_events_seconds_count{exception!=\"none\"}[$__rate_interval])) by (pod)",
     "legendFormat": "rps {{ pod }} - Error"
    }
   ]
  },
  {
   "title": "Reference Events - Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (pod, le) (rate(resource_reference_event_seconds_bucket{exception=\"none\"}[$__rate_interval])))",
     "legendFormat": "median - {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (pod, le) (rate(resource_reference_event_seconds_bucket{exception=\"none\"}[$__rate_interval])))",
     "legendFormat": "p95 - {{pod}}"
    }
   ]
  }
 ]
}