export const env = {
  // Services URLs
  EVENT_BY_ID_REFERENCE_URL: process.env.EVENT_BY_ID_REFERENCE_URL,
  CAST_VOTE_URL: process.env.REACT_APP_CAST_VOTE_URL,
  VOTE_RECEIPT_URL: process.env.REACT_APP_VOTE_RECEIPT_URL,
  BLOCKCHAIN_TIP_URL: process.env.REACT_APP_BLOCKCHAIN_TIP_URL,
  VOTING_POWER_URL: process.env.REACT_APP_VOTING_POWER_URL,
  LEADERBOARD_URL: process.env.REACT_APP_LEADERBOARD_URL,
  REFERENCE_DATA_URL: process.env.REACT_APP_EVENT_BY_ID_REFERENCE_URL,
  VERIFICATION_URL: process.env.REACT_APP_VERIFICATION_URL,

  // config vars
  TARGET_NETWORK: process.env.REACT_APP_TARGET_NETWORK,
  EVENT_ID: process.env.REACT_APP_EVENT_ID,
  CATEGORY_ID: process.env.REACT_APP_CATEGORY_ID,
  COMMIT_HASH: process.env.REACT_APP_COMMIT_HASH,
  SUPPORTED_WALLETS: (process.env.REACT_APP_SUPPORTED_WALLETS || '').split(',').filter((w) => !!w),
  ALWAYS_VISIBLE_WALLETS: (process.env.REACT_APP_ALWAYS_VISIBLE_WALLETS || '').split(',').filter((w) => !!w),
};
