export const ICONS = {
  arrowCircleLeft: "/icons/ArrowCircleLeft.svg",
  arrowCircleRight: "/icons/ArrowCircleRight.svg",
  arrowLeftIcon: "/icons/ArrowLeft.svg",
  closeIcon: "/icons/Close.svg",
  discordIcon: "/icons/Discord.svg",
  externalLinkIcon: "/icons/ExternalLink.svg",
  filterIcon: "/icons/Filter.svg",
  plusIcon: "/icons/Plus.svg",
  questionMarkCircleIcon: "/icons/QuestionMarkCircle.svg",
  searchIcon: "/icons/Search.svg",
  selectArrowIcon: "/icons/SelectArrow.svg",
  sortDescendingIcon: "/icons/SortDescending.svg",
  userIcon: "/icons/User.svg",
  userAddIcon: "/icons/UserAdd.svg",
  userGroupIcon: "/icons/UserGroup.svg",
  verifiedIcon: "/icons/Verified.svg",
  x_twitterIcon: "/icons/X-twitter.svg",
};
