{{ if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "voting-app.fullname" . }}
  labels:
    release: prometheus-stack
    {{- include "voting-app.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /actuator/prometheus
      port: http
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "voting-app.labels" . | nindent 6 }}
{{ end }}