version: '3.8'
services:
  follower-api:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/voting-ledger-follower-app:0.2.74
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CORS_ALLOWED_ORIGINS:http://localhost:8080
      - CARDANO_NETWORK=MAIN
      - ORGANISER_STAKE_ADDRESS=stake1
      - BIND_ON_EVENT_IDS=stake1
      - CARDANO_NODE_PROTOCOL_MAGIC=stake1
      - YACI_STORE_CARDANO_SYNC_START_BLOCK_HASH=
      - YACI_STORE_CARDANO_SYNC_START_SLOT=
    ports:
      - '9092:9092'
  verification-app:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/voting-verification-app:0.2.74
    restart: always
    environment:
      - LEDGER_FOLLOWER_APP_URL=http://follower-api:9090
    ports:
      - '9092:9092'
  verification-ui:
    image: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/voting-verification-app-ui:0.2.74
    restart: always
    environment:
      - VOTING_VERIFICATION_APP_SERVER_URL=http://verification-app:9092
      - REACT_APP_TARGET_NETWORK=preprod
    ports:
      - '8080:8080'
