name: Build and Publish Docker images (CIP 1694 Support Branch)

on:
  push:
    branches:
      - cip1694-prod-support
  workflow_dispatch:

env:
  PRIVATE_DOCKER_REGISTRY_URL: ${{ secrets.GITLAB_DOCKER_REGISTRY_URL }}
  PRIVATE_DOCKER_REGISTRY_USER: Deploy-Token
  PRIVATE_DOCKER_REGISTRY_PASS: ${{ secrets.GITLAB_PKG_REGISTRY_TOKEN }}

jobs:

  build-version:
    runs-on: self-hosted
    outputs:
      ARTIFACT_VERSION: ${{ steps.metadata.outputs.ARTIFACT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          pip install yq

      - name: Set extra environment and metadata
        id: metadata
        run: |
          CURRENT_VERSION=$(cat version.txt)
          SHORT_HASH=$(echo "$GITHUB_SHA" | cut -c -5)
          
          if [ ${{github.event_name}} == "pull_request" ]
          then
            PR_NUMBER=$(echo $GITHUB_REF | awk -F/ '{ print $3 }')
            echo "ARTIFACT_VERSION=${CURRENT_VERSION}-PR${PR_NUMBER}-$GITHUB_RUN_NUMBER" >> "$GITHUB_OUTPUT"
          elif [ ${{github.event_name}} == "push" ]
          then
            echo "ARTIFACT_VERSION=${CURRENT_VERSION}-$GITHUB_RUN_NUMBER-${SHORT_HASH}" >> "$GITHUB_OUTPUT"
          else
            BRANCH=${GITHUB_REF##*/}
            echo "BRANCH=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
            echo "ARTIFACT_VERSION=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"
          fi

  publish-voting-app:
    runs-on: self-hosted
    env:
      APP_NAME: voting-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Execute Gradle build
        working-directory: backend-services/${{ env.APP_NAME }}
        run: ./gradlew bootJar

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: backend-services/${{ env.APP_NAME }}
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}


  publish-voting-commitment-app:
    runs-on: self-hosted
    env:
      APP_NAME: vote-commitment-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Execute Gradle build
        working-directory: backend-services/${{ env.APP_NAME }}
        run: ./gradlew bootJar

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: backend-services/${{ env.APP_NAME }}
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}


  publish-voting-ledger-follower-app:
    runs-on: self-hosted
    env:
      APP_NAME: voting-ledger-follower-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Execute Gradle build
        working-directory: backend-services/${{ env.APP_NAME }}
        run: ./gradlew bootJar

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: backend-services/${{ env.APP_NAME }}
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}


  publish-voting-verification-app:
    runs-on: self-hosted
    env:
      APP_NAME: voting-verification-app
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Execute Gradle build
        working-directory: backend-services/${{ env.APP_NAME }}
        run: ./gradlew bootJar

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: backend-services/${{ env.APP_NAME }}
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}


  publish-user-verification-service:
    runs-on: self-hosted
    env:
      APP_NAME: user-verification-service
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Execute Gradle build
        working-directory: backend-services/${{ env.APP_NAME }}
        run: ./gradlew bootJar

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: backend-services/${{ env.APP_NAME }}
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}


  publish-voting-app-ui:
    runs-on: self-hosted
    env:
      APP_NAME: voting-app-ui
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{needs.build-version.outputs.ARTIFACT_VERSION}}
        with:
          context: ui/cip-1694
          push: true
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}

  publish-voting-verification-app-ui:
    runs-on: self-hosted
    env:
      APP_NAME: voting-verification-app-ui
    needs: build-version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Private Docker Hub Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}
          username: ${{ env.PRIVATE_DOCKER_REGISTRY_USER }}
          password: ${{ env.PRIVATE_DOCKER_REGISTRY_PASS }}

      - name: Public Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push docker image
        uses: docker/build-push-action@v4
        env:
          ARTIFACT_VERSION: ${{ needs.build-version.outputs.ARTIFACT_VERSION }}
          REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL: https://verification-api.dev.cf-cip1694-preprod.eu-west-1.metadata.dev.cf-deployments.org
          REACT_APP_TARGET_NETWORK: PREPROD
        with:
          context: ui/verification-app
          push: true
          build-args: |
            "REACT_APP_VERSION=${{ env.ARTIFACT_VERSION }}"
            "REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL=${{ env.REACT_APP_VOTING_VERIFICATION_APP_SERVER_URL }}"
            "REACT_APP_TARGET_NETWORK=${{ env.REACT_APP_TARGET_NETWORK }}"
          tags: |
            ${{ env.PRIVATE_DOCKER_REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.ARTIFACT_VERSION }}
