name: Voting App Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
  
jobs:
  commit-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Execute Gradle build
        working-directory: backend-services/voting-app
        run: ./gradlew build
